title: Jannik Vierling
email: "jannik.vierling@gmail.com"
description: >- 
baseurl: "/"
url: "https://jvierling.github.io" 
twitter_username: jekyllrb
github_username: jvierling
linkedin_username: Jannik Vierling
linkedin_url: jannik-vierling-0760b0248

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
